// @generated by protobuf-ts 2.0.6
// @generated from protobuf file "client_token.proto" (package "spotify.clienttoken.http.v0", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
import { ConnectivitySdkData } from "./connectivity";
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ClientTokenRequest
 */
export interface ClientTokenRequest {
    /**
     * @generated from protobuf field: spotify.clienttoken.http.v0.ClientTokenRequestType request_type = 1;
     */
    requestType: ClientTokenRequestType;
    /**
     * @generated from protobuf oneof: request
     */
    request: {
        oneofKind: "clientData";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.ClientDataRequest client_data = 2;
         */
        clientData: ClientDataRequest;
    } | {
        oneofKind: "challengeAnswers";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.ChallengeAnswersRequest challenge_answers = 3;
         */
        challengeAnswers: ChallengeAnswersRequest;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ClientDataRequest
 */
export interface ClientDataRequest {
    /**
     * @generated from protobuf field: string client_version = 1;
     */
    clientVersion: string;
    /**
     * @generated from protobuf field: string client_id = 2;
     */
    clientId: string;
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "connectivitySdkData";
        /**
         * @generated from protobuf field: spotify.clienttoken.data.v0.ConnectivitySdkData connectivity_sdk_data = 3;
         */
        connectivitySdkData: ConnectivitySdkData;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ChallengeAnswersRequest
 */
export interface ChallengeAnswersRequest {
    /**
     * @generated from protobuf field: string state = 1;
     */
    state: string;
    /**
     * @generated from protobuf field: repeated spotify.clienttoken.http.v0.ChallengeAnswer answers = 2;
     */
    answers: ChallengeAnswer[];
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ClientTokenResponse
 */
export interface ClientTokenResponse {
    /**
     * @generated from protobuf field: spotify.clienttoken.http.v0.ClientTokenResponseType response_type = 1;
     */
    responseType: ClientTokenResponseType;
    /**
     * @generated from protobuf oneof: response
     */
    response: {
        oneofKind: "grantedToken";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.GrantedTokenResponse granted_token = 2;
         */
        grantedToken: GrantedTokenResponse;
    } | {
        oneofKind: "challenges";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.ChallengesResponse challenges = 3;
         */
        challenges: ChallengesResponse;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.TokenDomain
 */
export interface TokenDomain {
    /**
     * @generated from protobuf field: string domain = 1;
     */
    domain: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.GrantedTokenResponse
 */
export interface GrantedTokenResponse {
    /**
     * @generated from protobuf field: string token = 1;
     */
    token: string;
    /**
     * @generated from protobuf field: int32 expires_after_seconds = 2;
     */
    expiresAfterSeconds: number;
    /**
     * @generated from protobuf field: int32 refresh_after_seconds = 3;
     */
    refreshAfterSeconds: number;
    /**
     * @generated from protobuf field: repeated spotify.clienttoken.http.v0.TokenDomain domains = 4;
     */
    domains: TokenDomain[];
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ChallengesResponse
 */
export interface ChallengesResponse {
    /**
     * @generated from protobuf field: string state = 1;
     */
    state: string;
    /**
     * @generated from protobuf field: repeated spotify.clienttoken.http.v0.Challenge challenges = 2;
     */
    challenges: Challenge[];
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ClientSecretParameters
 */
export interface ClientSecretParameters {
    /**
     * @generated from protobuf field: string salt = 1;
     */
    salt: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.EvaluateJSParameters
 */
export interface EvaluateJSParameters {
    /**
     * @generated from protobuf field: string code = 1;
     */
    code: string;
    /**
     * @generated from protobuf field: repeated string libraries = 2;
     */
    libraries: string[];
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.HashCashParameters
 */
export interface HashCashParameters {
    /**
     * @generated from protobuf field: int32 length = 1;
     */
    length: number;
    /**
     * @generated from protobuf field: string prefix = 2;
     */
    prefix: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.Challenge
 */
export interface Challenge {
    /**
     * @generated from protobuf field: spotify.clienttoken.http.v0.ChallengeType type = 1;
     */
    type: ChallengeType;
    /**
     * @generated from protobuf oneof: parameters
     */
    parameters: {
        oneofKind: "clientSecretParameters";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.ClientSecretParameters client_secret_parameters = 2;
         */
        clientSecretParameters: ClientSecretParameters;
    } | {
        oneofKind: "evaluateJsParameters";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.EvaluateJSParameters evaluate_js_parameters = 3;
         */
        evaluateJsParameters: EvaluateJSParameters;
    } | {
        oneofKind: "evaluateHashcashParameters";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.HashCashParameters evaluate_hashcash_parameters = 4;
         */
        evaluateHashcashParameters: HashCashParameters;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ClientSecretHMACAnswer
 */
export interface ClientSecretHMACAnswer {
    /**
     * @generated from protobuf field: string hmac = 1;
     */
    hmac: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.EvaluateJSAnswer
 */
export interface EvaluateJSAnswer {
    /**
     * @generated from protobuf field: string result = 1;
     */
    result: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.HashCashAnswer
 */
export interface HashCashAnswer {
    /**
     * @generated from protobuf field: string suffix = 1;
     */
    suffix: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ChallengeAnswer
 */
export interface ChallengeAnswer {
    /**
     * @generated from protobuf field: spotify.clienttoken.http.v0.ChallengeType ChallengeType = 1 [json_name = "ChallengeType"];
     */
    challengeType: ChallengeType;
    /**
     * @generated from protobuf oneof: answer
     */
    answer: {
        oneofKind: "clientSecret";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.ClientSecretHMACAnswer client_secret = 2;
         */
        clientSecret: ClientSecretHMACAnswer;
    } | {
        oneofKind: "evaluateJs";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.EvaluateJSAnswer evaluate_js = 3;
         */
        evaluateJs: EvaluateJSAnswer;
    } | {
        oneofKind: "hashCash";
        /**
         * @generated from protobuf field: spotify.clienttoken.http.v0.HashCashAnswer hash_cash = 4;
         */
        hashCash: HashCashAnswer;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.clienttoken.http.v0.ClientTokenBadRequest
 */
export interface ClientTokenBadRequest {
    /**
     * @generated from protobuf field: string message = 1;
     */
    message: string;
}
/**
 * @generated from protobuf enum spotify.clienttoken.http.v0.ClientTokenRequestType
 */
export enum ClientTokenRequestType {
    /**
     * @generated from protobuf enum value: REQUEST_UNKNOWN = 0;
     */
    REQUEST_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: REQUEST_CLIENT_DATA_REQUEST = 1;
     */
    REQUEST_CLIENT_DATA_REQUEST = 1,
    /**
     * @generated from protobuf enum value: REQUEST_CHALLENGE_ANSWERS_REQUEST = 2;
     */
    REQUEST_CHALLENGE_ANSWERS_REQUEST = 2
}
/**
 * @generated from protobuf enum spotify.clienttoken.http.v0.ClientTokenResponseType
 */
export enum ClientTokenResponseType {
    /**
     * @generated from protobuf enum value: RESPONSE_UNKNOWN = 0;
     */
    RESPONSE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: RESPONSE_GRANTED_TOKEN_RESPONSE = 1;
     */
    RESPONSE_GRANTED_TOKEN_RESPONSE = 1,
    /**
     * @generated from protobuf enum value: RESPONSE_CHALLENGES_RESPONSE = 2;
     */
    RESPONSE_CHALLENGES_RESPONSE = 2
}
/**
 * @generated from protobuf enum spotify.clienttoken.http.v0.ChallengeType
 */
export enum ChallengeType {
    /**
     * @generated from protobuf enum value: CHALLENGE_UNKNOWN = 0;
     */
    CHALLENGE_UNKNOWN = 0,
    /**
     * @generated from protobuf enum value: CHALLENGE_CLIENT_SECRET_HMAC = 1;
     */
    CHALLENGE_CLIENT_SECRET_HMAC = 1,
    /**
     * @generated from protobuf enum value: CHALLENGE_EVALUATE_JS = 2;
     */
    CHALLENGE_EVALUATE_JS = 2,
    /**
     * @generated from protobuf enum value: CHALLENGE_HASH_CASH = 3;
     */
    CHALLENGE_HASH_CASH = 3
}
// @generated message type with reflection information, may provide speed optimized methods
class ClientTokenRequest$Type extends MessageType<ClientTokenRequest> {
    constructor() {
        super("spotify.clienttoken.http.v0.ClientTokenRequest", [
            { no: 1, name: "request_type", kind: "enum", T: () => ["spotify.clienttoken.http.v0.ClientTokenRequestType", ClientTokenRequestType] },
            { no: 2, name: "client_data", kind: "message", oneof: "request", T: () => ClientDataRequest },
            { no: 3, name: "challenge_answers", kind: "message", oneof: "request", T: () => ChallengeAnswersRequest }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ClientTokenRequest
 */
export const ClientTokenRequest = new ClientTokenRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientDataRequest$Type extends MessageType<ClientDataRequest> {
    constructor() {
        super("spotify.clienttoken.http.v0.ClientDataRequest", [
            { no: 1, name: "client_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "client_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "connectivity_sdk_data", kind: "message", oneof: "data", T: () => ConnectivitySdkData }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ClientDataRequest
 */
export const ClientDataRequest = new ClientDataRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChallengeAnswersRequest$Type extends MessageType<ChallengeAnswersRequest> {
    constructor() {
        super("spotify.clienttoken.http.v0.ChallengeAnswersRequest", [
            { no: 1, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "answers", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => ChallengeAnswer }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ChallengeAnswersRequest
 */
export const ChallengeAnswersRequest = new ChallengeAnswersRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientTokenResponse$Type extends MessageType<ClientTokenResponse> {
    constructor() {
        super("spotify.clienttoken.http.v0.ClientTokenResponse", [
            { no: 1, name: "response_type", kind: "enum", T: () => ["spotify.clienttoken.http.v0.ClientTokenResponseType", ClientTokenResponseType] },
            { no: 2, name: "granted_token", kind: "message", oneof: "response", T: () => GrantedTokenResponse },
            { no: 3, name: "challenges", kind: "message", oneof: "response", T: () => ChallengesResponse }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ClientTokenResponse
 */
export const ClientTokenResponse = new ClientTokenResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class TokenDomain$Type extends MessageType<TokenDomain> {
    constructor() {
        super("spotify.clienttoken.http.v0.TokenDomain", [
            { no: 1, name: "domain", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.TokenDomain
 */
export const TokenDomain = new TokenDomain$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GrantedTokenResponse$Type extends MessageType<GrantedTokenResponse> {
    constructor() {
        super("spotify.clienttoken.http.v0.GrantedTokenResponse", [
            { no: 1, name: "token", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "expires_after_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "refresh_after_seconds", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "domains", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => TokenDomain }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.GrantedTokenResponse
 */
export const GrantedTokenResponse = new GrantedTokenResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChallengesResponse$Type extends MessageType<ChallengesResponse> {
    constructor() {
        super("spotify.clienttoken.http.v0.ChallengesResponse", [
            { no: 1, name: "state", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "challenges", kind: "message", repeat: 1 /*RepeatType.PACKED*/, T: () => Challenge }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ChallengesResponse
 */
export const ChallengesResponse = new ChallengesResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientSecretParameters$Type extends MessageType<ClientSecretParameters> {
    constructor() {
        super("spotify.clienttoken.http.v0.ClientSecretParameters", [
            { no: 1, name: "salt", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ClientSecretParameters
 */
export const ClientSecretParameters = new ClientSecretParameters$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EvaluateJSParameters$Type extends MessageType<EvaluateJSParameters> {
    constructor() {
        super("spotify.clienttoken.http.v0.EvaluateJSParameters", [
            { no: 1, name: "code", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "libraries", kind: "scalar", repeat: 2 /*RepeatType.UNPACKED*/, T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.EvaluateJSParameters
 */
export const EvaluateJSParameters = new EvaluateJSParameters$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HashCashParameters$Type extends MessageType<HashCashParameters> {
    constructor() {
        super("spotify.clienttoken.http.v0.HashCashParameters", [
            { no: 1, name: "length", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "prefix", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.HashCashParameters
 */
export const HashCashParameters = new HashCashParameters$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Challenge$Type extends MessageType<Challenge> {
    constructor() {
        super("spotify.clienttoken.http.v0.Challenge", [
            { no: 1, name: "type", kind: "enum", T: () => ["spotify.clienttoken.http.v0.ChallengeType", ChallengeType] },
            { no: 2, name: "client_secret_parameters", kind: "message", oneof: "parameters", T: () => ClientSecretParameters },
            { no: 3, name: "evaluate_js_parameters", kind: "message", oneof: "parameters", T: () => EvaluateJSParameters },
            { no: 4, name: "evaluate_hashcash_parameters", kind: "message", oneof: "parameters", T: () => HashCashParameters }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.Challenge
 */
export const Challenge = new Challenge$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientSecretHMACAnswer$Type extends MessageType<ClientSecretHMACAnswer> {
    constructor() {
        super("spotify.clienttoken.http.v0.ClientSecretHMACAnswer", [
            { no: 1, name: "hmac", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ClientSecretHMACAnswer
 */
export const ClientSecretHMACAnswer = new ClientSecretHMACAnswer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class EvaluateJSAnswer$Type extends MessageType<EvaluateJSAnswer> {
    constructor() {
        super("spotify.clienttoken.http.v0.EvaluateJSAnswer", [
            { no: 1, name: "result", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.EvaluateJSAnswer
 */
export const EvaluateJSAnswer = new EvaluateJSAnswer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class HashCashAnswer$Type extends MessageType<HashCashAnswer> {
    constructor() {
        super("spotify.clienttoken.http.v0.HashCashAnswer", [
            { no: 1, name: "suffix", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.HashCashAnswer
 */
export const HashCashAnswer = new HashCashAnswer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChallengeAnswer$Type extends MessageType<ChallengeAnswer> {
    constructor() {
        super("spotify.clienttoken.http.v0.ChallengeAnswer", [
            { no: 1, name: "ChallengeType", kind: "enum", jsonName: "ChallengeType", T: () => ["spotify.clienttoken.http.v0.ChallengeType", ChallengeType] },
            { no: 2, name: "client_secret", kind: "message", oneof: "answer", T: () => ClientSecretHMACAnswer },
            { no: 3, name: "evaluate_js", kind: "message", oneof: "answer", T: () => EvaluateJSAnswer },
            { no: 4, name: "hash_cash", kind: "message", oneof: "answer", T: () => HashCashAnswer }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ChallengeAnswer
 */
export const ChallengeAnswer = new ChallengeAnswer$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ClientTokenBadRequest$Type extends MessageType<ClientTokenBadRequest> {
    constructor() {
        super("spotify.clienttoken.http.v0.ClientTokenBadRequest", [
            { no: 1, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.http.v0.ClientTokenBadRequest
 */
export const ClientTokenBadRequest = new ClientTokenBadRequest$Type();
