// @generated by protobuf-ts 2.0.6
// @generated from protobuf file "connectivity.proto" (package "spotify.clienttoken.data.v0", syntax proto3)
// tslint:disable
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message spotify.clienttoken.data.v0.ConnectivitySdkData
 */
export interface ConnectivitySdkData {
    /**
     * @generated from protobuf field: spotify.clienttoken.data.v0.PlatformSpecificData platform_specific_data = 1;
     */
    platformSpecificData?: PlatformSpecificData;
    /**
     * @generated from protobuf field: string device_id = 2;
     */
    deviceId: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.data.v0.PlatformSpecificData
 */
export interface PlatformSpecificData {
    /**
     * @generated from protobuf oneof: data
     */
    data: {
        oneofKind: "android";
        /**
         * @generated from protobuf field: spotify.clienttoken.data.v0.NativeAndroidData android = 1;
         */
        android: NativeAndroidData;
    } | {
        oneofKind: "ios";
        /**
         * @generated from protobuf field: spotify.clienttoken.data.v0.NativeIOSData ios = 2;
         */
        ios: NativeIOSData;
    } | {
        oneofKind: "windows";
        /**
         * @generated from protobuf field: spotify.clienttoken.data.v0.NativeWindowsData windows = 4;
         */
        windows: NativeWindowsData;
    } | {
        oneofKind: undefined;
    };
}
/**
 * @generated from protobuf message spotify.clienttoken.data.v0.NativeAndroidData
 */
export interface NativeAndroidData {
    /**
     * @generated from protobuf field: int32 major_sdk_version = 1;
     */
    majorSdkVersion: number;
    /**
     * @generated from protobuf field: int32 minor_sdk_version = 2;
     */
    minorSdkVersion: number;
    /**
     * @generated from protobuf field: int32 patch_sdk_version = 3;
     */
    patchSdkVersion: number;
    /**
     * @generated from protobuf field: uint32 api_version = 4;
     */
    apiVersion: number;
    /**
     * @generated from protobuf field: spotify.clienttoken.data.v0.Screen screen_dimensions = 5;
     */
    screenDimensions?: Screen;
}
/**
 * @generated from protobuf message spotify.clienttoken.data.v0.NativeIOSData
 */
export interface NativeIOSData {
    /**
     * @generated from protobuf field: int32 user_interface_idiom = 1;
     */
    userInterfaceIdiom: number;
    /**
     * @generated from protobuf field: bool target_iphone_simulator = 2;
     */
    targetIphoneSimulator: boolean;
    /**
     * @generated from protobuf field: string hw_machine = 3;
     */
    hwMachine: string;
    /**
     * @generated from protobuf field: string system_version = 4;
     */
    systemVersion: string;
    /**
     * @generated from protobuf field: string simulator_model_identifier = 5;
     */
    simulatorModelIdentifier: string;
}
/**
 * @generated from protobuf message spotify.clienttoken.data.v0.NativeWindowsData
 */
export interface NativeWindowsData {
    /**
     * @generated from protobuf field: int32 something1 = 1;
     */
    something1: number;
    /**
     * @generated from protobuf field: int32 something3 = 3;
     */
    something3: number;
    /**
     * @generated from protobuf field: int32 something4 = 4;
     */
    something4: number;
    /**
     * @generated from protobuf field: int32 something6 = 6;
     */
    something6: number;
    /**
     * @generated from protobuf field: int32 something7 = 7;
     */
    something7: number;
    /**
     * @generated from protobuf field: int32 something8 = 8;
     */
    something8: number;
    /**
     * @generated from protobuf field: bool something10 = 10;
     */
    something10: boolean;
}
/**
 * @generated from protobuf message spotify.clienttoken.data.v0.Screen
 */
export interface Screen {
    /**
     * @generated from protobuf field: int32 width = 1;
     */
    width: number;
    /**
     * @generated from protobuf field: int32 height = 2;
     */
    height: number;
    /**
     * @generated from protobuf field: int32 density = 3;
     */
    density: number;
}
// @generated message type with reflection information, may provide speed optimized methods
class ConnectivitySdkData$Type extends MessageType<ConnectivitySdkData> {
    constructor() {
        super("spotify.clienttoken.data.v0.ConnectivitySdkData", [
            { no: 1, name: "platform_specific_data", kind: "message", T: () => PlatformSpecificData },
            { no: 2, name: "device_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.data.v0.ConnectivitySdkData
 */
export const ConnectivitySdkData = new ConnectivitySdkData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class PlatformSpecificData$Type extends MessageType<PlatformSpecificData> {
    constructor() {
        super("spotify.clienttoken.data.v0.PlatformSpecificData", [
            { no: 1, name: "android", kind: "message", oneof: "data", T: () => NativeAndroidData },
            { no: 2, name: "ios", kind: "message", oneof: "data", T: () => NativeIOSData },
            { no: 4, name: "windows", kind: "message", oneof: "data", T: () => NativeWindowsData }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.data.v0.PlatformSpecificData
 */
export const PlatformSpecificData = new PlatformSpecificData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NativeAndroidData$Type extends MessageType<NativeAndroidData> {
    constructor() {
        super("spotify.clienttoken.data.v0.NativeAndroidData", [
            { no: 1, name: "major_sdk_version", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "minor_sdk_version", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "patch_sdk_version", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "api_version", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 5, name: "screen_dimensions", kind: "message", T: () => Screen }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.data.v0.NativeAndroidData
 */
export const NativeAndroidData = new NativeAndroidData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NativeIOSData$Type extends MessageType<NativeIOSData> {
    constructor() {
        super("spotify.clienttoken.data.v0.NativeIOSData", [
            { no: 1, name: "user_interface_idiom", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "target_iphone_simulator", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 3, name: "hw_machine", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "system_version", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 5, name: "simulator_model_identifier", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.data.v0.NativeIOSData
 */
export const NativeIOSData = new NativeIOSData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class NativeWindowsData$Type extends MessageType<NativeWindowsData> {
    constructor() {
        super("spotify.clienttoken.data.v0.NativeWindowsData", [
            { no: 1, name: "something1", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "something3", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 4, name: "something4", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 6, name: "something6", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 7, name: "something7", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 8, name: "something8", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 10, name: "something10", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.data.v0.NativeWindowsData
 */
export const NativeWindowsData = new NativeWindowsData$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Screen$Type extends MessageType<Screen> {
    constructor() {
        super("spotify.clienttoken.data.v0.Screen", [
            { no: 1, name: "width", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 2, name: "height", kind: "scalar", T: 5 /*ScalarType.INT32*/ },
            { no: 3, name: "density", kind: "scalar", T: 5 /*ScalarType.INT32*/ }
        ]);
    }
}
/**
 * @generated MessageType for protobuf message spotify.clienttoken.data.v0.Screen
 */
export const Screen = new Screen$Type();
